version: '3.8'
services:
  books-service:
    build: ./services/books-service
    ports:
      - "3001:3000"
  orders-service:
    build: ./services/orders-service
    ports:
      - "3002:3000"
  users-service:                                                                                                                                             
    build: ./services/users-service                                                                                                                           
    ports:                                                                                                                                                   
      - "3003:3000"                                                                                                                                          
  frontend:                                                                                                                                            
    build: ./frontend                                                                                                                          
    ports:                                                                                                                                                   
      - "3000:3000" 
